version: '3.9'
services:
  jenkins:
    restart: on-failure:10
    image: jenkins/jenkins:latest-jdk11
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
     - jenkins:/var/jenkins_home
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - jenkins
volumes:
     jenkins:
